BOARD := uno
#ARDUINODIR := /usr/share/arduino
ARDUINODIR := /Applications/Arduino.app/Contents
#SERIALDEV := /dev/ttyACM0
SERIALDEV := /dev/tty.usbmodem262471
BOARD_UPLOAD_SPEED := 115200
#SHELL := /system/bin/sh
include arduino.mk
